### ISSUE TITLE
Publish 0.1.26

### ISSUE THREAD

**Issue by lefou** [alexarchambault/mill-native-image#72]
The version is tagged, but release errored out.

https://github.com/alexarchambault/mill-native-image/actions/runs/6590419696/job/17910505020

@alexarchambault Probably gpg related?

**Comment by carlosedp** [comment]
I tried to release and also bump the vcs plugin but it's still failing...

**Comment by alexarchambault** [comment]
Thanks for the report / the attempts to fix that, @lefou and @carlosedp.

https://github.com/alexarchambault/mill-native-image/commit/3917eae3c2777a040bf3667e5c0a214fd132cac7 and https://github.com/alexarchambault/mill-native-image/commit/aaf3c215ad88289bcd24df20ed55611d38ea2848 seems to [have fixed things](https://github.com/alexarchambault/mill-native-image/actions/runs/6695340115/job/18190696864)

**Comment by lefou** [comment]
Thanks @alexarchambault . Was there any communication with Sonatype necessary to switch to the `s01`-URL, or did it "just work"?

I think you may want to add the release to the release pages, so others will be aware of the new version.

**Comment by alexarchambault** [comment]
@lefou I opened an issue on the Sonatype JIRA some time ago, to migrate some of my "profiles" to it. I thought that meant I had to use `s01` for those profiles, but it seems the legacy server still works for those (alongside `s01`). So only updating the server URL here was enough for things to things to work immediately.

> I think you may want to add the release to the release pages, so others will be aware of the new version.

👍
